harnessApiVersion: '1.0'
type: PIPELINE
description: DeploymentPipeline
pipelineStages:
- type: APPROVAL
  name: Approval 0
  parallel: false
  properties:
    userGroups:
    - Account Administrator
    workflowVariables: null
    stageName: STAGE 1
    timeoutMillis: 86400000
    approvalStateType: USER_GROUP
    sweepingOutputName: ''
  skipCondition:
    type: DO_NOT_SKIP
  stageName: STAGE 1
- type: ENV_STATE
  name: CIWorkFlow
  parallel: false
  skipCondition:
    type: DO_NOT_SKIP
  stageName: STAGE 2
  workflowName: CIWorkFlow
- type: APPROVAL
  name: Approval 2
  parallel: false
  properties:
    userGroups:
    - Account Administrator
    workflowVariables: null
    stageName: STAGE 3
    timeoutMillis: 86400000
    approvalStateType: USER_GROUP
    sweepingOutputName: ''
  skipCondition:
    type: DO_NOT_SKIP
  stageName: STAGE 3
- type: ENV_STATE
  name: CDWorkFlow
  parallel: false
  skipCondition:
    type: DO_NOT_SKIP
  stageName: STAGE 4
  workflowName: CDWorkFlow
- type: APPROVAL
  name: Approval 4
  parallel: false
  properties:
    workflowVariables: null
    approvalStateParams:
      serviceNowApprovalParams:
        approval:
          conditions:
            state:
            - Scheduled
          operator: AND
        rejection:
          conditions:
            state:
            - Canceled
          operator: AND
        snowConnectorId: CQxYoHJxTTubFObed1YXCg
        ticketType: CHANGE_REQUEST
        changeWindowPresent: false
        changeWindowStartField: ''
        changeWindowEndField: ''
        issueNumber: CHG0030017
    stageName: STAGE 4
    timeoutMillis: 86400000
    approvalStateType: SERVICENOW
  skipCondition:
    type: DO_NOT_SKIP
  stageName: STAGE 4
- type: ENV_STATE
  name: PreProd Deployment
  parallel: false
  skipCondition:
    type: DO_NOT_SKIP
  stageName: STAGE 5
  workflowName: CDPreProdWorkflow
