harnessApiVersion: '1.0'
type: PIPELINE
description: DeploymentPipeline
pipelineStages:
- type: ENV_STATE
  name: CIWorkFlow
  parallel: false
  skipCondition:
    type: DO_NOT_SKIP
  stageName: STAGE 1
  workflowName: CIWorkFlow
